export enum EmailEvent {
  // Account & Identity
  ACCOUNT_CREATED_VERIFY_EMAIL = 'ACCOUNT_CREATED_VERIFY_EMAIL',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_CHANGED_CONFIRMATION = 'PASSWORD_CHANGED_CONFIRMATION',

  // Orders & Payments
  ORDER_CONFIRMED_CUSTOMER = 'ORDER_CONFIRMED_CUSTOMER',
  ORDER_CONFIRMED_ADMIN = 'ORDER_CONFIRMED_ADMIN',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // Fulfillment
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED_CUSTOMER = 'ORDER_CANCELLED_CUSTOMER',
  ORDER_CANCELLED_ADMIN = 'ORDER_CANCELLED_ADMIN',

  // Refunds
  REFUND_COMPLETED = 'REFUND_COMPLETED',

  // Operations
  LOW_STOCK_ALERT = 'LOW_STOCK_ALERT',
  OUT_OF_STOCK_ALERT = 'OUT_OF_STOCK_ALERT',
}
